### ISSUE TITLE
Use of undeclared identifier 'UIApplication'

### ISSUE THREAD

**Issue by samcampisi** [Gaspard-Bruno/react-native-static-safe-area-insets#1]
I'm trying to install and link react-native-static-safe-area-insets.

I installed the library via npm:
npm install react-native-static-safe-area-insets

and followed the steps to link it manually. However, when I try to rebuild in xcode I get the following error:

<img width="1654" alt="screenshot 2018-12-18 at 14 11 00" src="https://user-images.githubusercontent.com/42766924/50156377-ff39b000-02ce-11e9-8753-f2fb83a75ef4.png">

What might be happening?

I have react native 0.57 and an iPhone X and library in version 1.1.0

**Comment by jpamarohorta** [comment]
Fixed by [release 1.1.3](https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets/releases/tag/v1.1.3)
