### ISSUE TITLE
Shouldn't those inset values update on orientation change?

### ISSUE THREAD

**Issue by grifotv** [Gaspard-Bruno/react-native-static-safe-area-insets#10]
on an iPhone XE (iOS 12.0), I'm getting the following values
```
PORTRAIT
{safeAreaInsetsRight: 0, safeAreaInsetsTop: 44, safeAreaInsetsBottom: 34, safeAreaInsetsLeft: 0, getConstants: ƒ}
```

```
LANDSCAPE-RIGHT
{safeAreaInsetsRight: 44, safeAreaInsetsTop: 0, safeAreaInsetsBottom: 21, safeAreaInsetsLeft: 44, getConstants: ƒ}
```

```
LANDSCAPE-LEFT
{safeAreaInsetsRight: 44, safeAreaInsetsTop: 0, safeAreaInsetsBottom: 21, safeAreaInsetsLeft: 44, getConstants: ƒ}
```

But on orientation change, the inset values are always based on the orientation when the app started.

**Comment by CarlosUvaSilva** [comment]
hello @grifotv

at the moment we don't support orientation change, although we want to implement it in the near future. 
Maybe help us out and open a PR? :)

**Comment by grifotv** [comment]
Thanks for getting back. I'd love to help but don't have a lot of native experience. I'll have a go anyway and will let you know.
