### ISSUE TITLE
Support for "immersion" mode

### ISSUE THREAD

**Issue by AdamGerthel** [Gaspard-Bruno/react-native-static-safe-area-insets#14]
Does this package support ["immersion" mode](https://developer.android.com/training/system-ui/immersive#immersive) on Android? I.e. do the insets take the visibility of the navigation bar into consideration?

**Comment by jpamarohorta** [comment]
Hello, I'm not sure. The library uses the [WindowInsets](https://developer.android.com/reference/android/view/WindowInsets) to get the values but I don't know how that works in immersion mode.

**Comment by jpamarohorta** [comment]
Hello, release [2.2.0](https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets/releases/tag/v2.2.0) now allows the insets to be correctly fetched in immersive mode.
