### ISSUE TITLE
Wrong insets for android

### ISSUE THREAD

**Issue by matt-way** [Gaspard-Bruno/react-native-static-safe-area-insets#16]
Not sure why, but I'm getting really large inset values on android (top and bottom). Any ideas what the problem could be?

**Comment by jpamarohorta** [comment]
A fix to the Android values has just been merged and published in version [2.1.0](https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets/releases/tag/v2.1.0), can you check if this issue has been fixed with it?

**Comment by matt-way** [comment]
Thank you
