### ISSUE TITLE
Bottom insets on Pixel 3

### ISSUE THREAD

**Issue by BouweCeunen** [Gaspard-Bruno/react-native-static-safe-area-insets#18]
I'm wondering why there's a bottom inset of 48 on a Pixel 3 on my simulator? It creates extra margin beneath the icons, because I implemented this way. There's no bottom inset on Pixel 3 right? This is also the case for Android tablets.

![image](https://user-images.githubusercontent.com/5576686/80822283-ab391e00-8bda-11ea-964d-5bdfbe4b2ced.png)

**Comment by alexpoon2000** [comment]
Do you have solution? I have the same issue with all android devices. It seems added extra 48 pixel bottom space to all android devices. I tried to remove the extra 48 for Android and move down my bottom menu as well. But I found it is not able to click the menu after I do this.

**Comment by BouweCeunen** [comment]
I just hardcoded it based on which OS the app is running on. Did not find a good solution to this yet.

**Comment by Rehubbard** [comment]
I am having the same issue. Using `StaticSafeAreaInsets.safeAreaInsetsBottom` always gives an incorrect value of 48 on Android.

Maybe it's considering the bottom Android UI navigation as a SafeArea?

**Comment by MaratSHU** [comment]
It seems to be you are right, Rehubbard. In real Android device (realme 6) `safeAreaInsetsBottom` equals to "44".
```
"react-native": "^0.61.5", 
"react-native-static-safe-area-insets": "^2.1.1",
```

**Comment by mrousavy** [comment]
I believe the navigation bar is intentionally reported as safe area. If it's consistent then you can just ignore the bottom safe area on Android devices, since those don't have safe areas like iPhones anyway, no?

**Comment by jpamarohorta** [comment]
Hello, release [2.2.0](https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets/releases/tag/v2.2.0) now uses only returns insets if the app is in fullscreen or immersive modes, so this issue should have been fixed.
