### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by jpike88** [Gaspard-Bruno/react-native-static-safe-area-insets#25]
I'm seeing hanging PRs, and having issues related to this lib. Should I just avoid it?

**Comment by daveyjones** [comment]
Yeah I had to stop using this but found that `initialWindowMetrics` from the `react-native-safe-area-context` was an ideal replacement. Also, `react-native-safe-area-context` is a dependency of React Navigation if you happen to be using that for navigation, so you may already have it installed.

**Comment by nabilfreeman** [comment]
Thank you for shipping a gradle 7 fix regardless! Advice noted about moving away.

**Comment by jpamarohorta** [comment]
Hello, this repo lacked support on our side and I'm sorry for that. We now published a new version [2.2.0](https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets/releases/tag/v2.2.0) that should have answered to most ongoing issues and we will try to keep the library up to date from now on. Thank you for all the contributions!
